version: "3.8"

services:
  webapp:
    build: ./web_service
    container_name: webapp_container
    ports:
      - "5000:5000"
    environment:
      - DB_SERVICE_URL=http://dbapp_container:5001/record
    depends_on:
      - dbapp
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  dbapp:
    build: ./db_service
    container_name: dbapp_container
    ports:
      - "5001:5001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge
